/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LifeSave.Charity;

import LifeSave.Utilities.ValidateDateOfBirth;
import LifeSave.Utilities.ValidateEmailTextField;
import LifeSave.Utilities.ValidateNumbers;
import LifeSave.Utilities.ValidatePhoneNumber;
import LifeSave.Utilities.ValidateStrings;
import LifeSave.Person.Person;
import LifeSave.UserAccounts.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jkoti
 */
public class CreateCharityProfileJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    
    /**
     * Creates new form CreateCharityProfileJPanel
     */
    public CreateCharityProfileJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        addInputVerifiers();
        sponsorNF.setText(userAccount.getPerson().getName());
        donorName.setVisible(true);
    }
    
    
    private void addInputVerifiers() {
          
        InputVerifier stringValidation = new ValidateStrings();
        sponsorNF.setInputVerifier(stringValidation);
        addressF.setInputVerifier(stringValidation);
        cityF.setInputVerifier(stringValidation);
        
        InputVerifier dobValidtion = new ValidateDateOfBirth();
        sponsorDOBF.setInputVerifier(dobValidtion);
        
        InputVerifier numberValidation = new ValidateNumbers();
        zipCodeF.setInputVerifier(numberValidation);
        
        InputVerifier phnumberValidation = new ValidatePhoneNumber();
        phoneNumF.setInputVerifier(phnumberValidation);
         
            InputVerifier emailValidtion = new ValidateEmailTextField();
            emailIDF.setInputVerifier(emailValidtion);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateOfBirth = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        addressF = new javax.swing.JTextField();
        town = new javax.swing.JLabel();
        cityF = new javax.swing.JTextField();
        zipCode = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        createYourProfile = new javax.swing.JLabel();
        donorName = new javax.swing.JLabel();
        sponsorNF = new javax.swing.JTextField();
        zipCodeF = new javax.swing.JTextField();
        emailID = new javax.swing.JLabel();
        emailIDF = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        phoneNumF = new javax.swing.JTextField();
        createProfileButton = new javax.swing.JButton();
        sponsorDOBF = new javax.swing.JFormattedTextField();
        manageEnt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        dateOfBirth.setText("Date Of Birth (MM/DD/YYYY):");

        address.setText("Address: ");

        town.setText("Town/City: ");

        zipCode.setText("Zip Code:");

        backJButton.setText("<< back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        createYourProfile.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        createYourProfile.setText("Create Your Profile");

        donorName.setText("Full Name:");

        sponsorNF.setEditable(false);
        sponsorNF.setEnabled(false);

        emailID.setText("Email Address:");

        phoneNumber.setText("Phone Number:");

        createProfileButton.setText("Create Profile ");
        createProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProfileButtonActionPerformed(evt);
            }
        });

        manageEnt.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        manageEnt.setText("Charity Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backJButton)
                .addGap(38, 254, Short.MAX_VALUE)
                .addComponent(createProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(418, 418, 418))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(town))
                            .addComponent(emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(donorName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumber)
                            .addComponent(createYourProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phoneNumF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sponsorDOBF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(zipCodeF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cityF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailIDF, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(sponsorNF, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(manageEnt)
                .addGap(18, 18, 18)
                .addComponent(createYourProfile)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donorName)
                    .addComponent(sponsorNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateOfBirth)
                    .addComponent(sponsorDOBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(addressF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(town)
                    .addComponent(cityF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailID)
                    .addComponent(emailIDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCodeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProfileButton)
                    .addComponent(backJButton))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void createProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProfileButtonActionPerformed
        Person person = userAccount.getPerson();
        
        if( addressF.getText().trim().isEmpty() ||
             cityF.getText().trim().isEmpty() ||
             emailIDF.getText().trim().isEmpty() ||
           phoneNumF.getText().trim().isEmpty() || 
             sponsorDOBF.getText().trim().isEmpty() ||
            zipCodeF.getText().trim().isEmpty() ) 
        {
        JOptionPane.showMessageDialog(null, "Please Enter data in all the fields");
           return;        
        }
        
        try
        {
          DateFormat dateFormat =  new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        Date dob =  dateFormat.parse(sponsorDOBF.getText());
        if(dob.after(date) || dob.equals(date))
        {
         JOptionPane.showMessageDialog(null, "Please Enter valid Date of Birth");
           return;    
        }
            person.setDob(dateFormat.parse(sponsorDOBF.getText()));
            person.setAdd1(addressF.getText());
            person.setCity(cityF.getText());
            person.setZipCode(zipCodeF.getText());
            person.setEmailId(emailIDF.getText());
            person.setPhoneNumber(phoneNumF.getText());      
            
            JOptionPane.showMessageDialog(null, "Your Profile has been created successfully", "success", JOptionPane.PLAIN_MESSAGE);
            resetFields();       
        }
        catch(ParseException pe)
        {
           JOptionPane.showMessageDialog(null, "Please Enter valid date of Birth!");
           return;   
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, "Please Enter valid data in all the fields");
           return;     
        }
    }//GEN-LAST:event_createProfileButtonActionPerformed

public void resetFields()
{
    sponsorNF.setText("");
    sponsorDOBF.setText("");
    addressF.setText("");
    cityF.setText("");
    zipCodeF.setText("");
    emailIDF.setText("");
    phoneNumF.setText("");
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressF;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField cityF;
    private javax.swing.JButton createProfileButton;
    private javax.swing.JLabel createYourProfile;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JLabel donorName;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDF;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField phoneNumF;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JFormattedTextField sponsorDOBF;
    private javax.swing.JTextField sponsorNF;
    private javax.swing.JLabel town;
    private javax.swing.JLabel zipCode;
    private javax.swing.JTextField zipCodeF;
    // End of variables declaration//GEN-END:variables
}
