/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package UI.OrganSeeker;

import LifeSaveMain.EcoSystem;
import LifeSave.Enterprises.Enterprise;
import LifeSave.Enterprises.CharitableTrust;
import LifeSave.Network.Network;
import LifeSave.Organizations.Organization;
import LifeSave.Person.OrganSeeker;
import LifeSave.UserAccounts.UserAccount;
import LifeSave.WorkQueues.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author parthkalani
 */
public class ManageVitalsJPanel extends javax.swing.JPanel {
     
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private OrganSeeker person;
    private EcoSystem ecoSystem;

    public ManageVitalsJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        person = (OrganSeeker)userAccount.getPerson();
        this.ecoSystem = ecoSystem;
        vitalSignPanel.setVisible(false);

    }
    
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shareInfoGroup = new javax.swing.ButtonGroup();
        hasSensorGroup = new javax.swing.ButtonGroup();
        getAlertsGroup = new javax.swing.ButtonGroup();
        hasCardiacProbGroup = new javax.swing.ButtonGroup();
        sendToDoctorGroup = new javax.swing.ButtonGroup();
        getAlertFromHH = new javax.swing.JLabel();
        shareVitalInfoJRadioYes = new javax.swing.JRadioButton();
        shareVitalInfoJRadioNo = new javax.swing.JRadioButton();
        shareInfo = new javax.swing.JLabel();
        submitVitalSignsJBtn = new javax.swing.JButton();
        cancelJBtn = new javax.swing.JButton();
        vitalSignPanel = new javax.swing.JPanel();
        hasSensorRadioYes = new javax.swing.JRadioButton();
        respRateCheckBox = new javax.swing.JCheckBox();
        getAlertJRadioYes = new javax.swing.JRadioButton();
        sysBPCheckBox = new javax.swing.JCheckBox();
        weightCheckBox = new javax.swing.JCheckBox();
        getAlert = new javax.swing.JLabel();
        sensorDevice = new javax.swing.JLabel();
        getAlertJRadioNo = new javax.swing.JRadioButton();
        vitalSignsTrck = new javax.swing.JLabel();
        hasSensorRadioNo = new javax.swing.JRadioButton();
        heartRateChckBox = new javax.swing.JCheckBox();
        backJButton = new javax.swing.JButton();
        cardiacProblems = new javax.swing.JLabel();
        hasCardiacYes = new javax.swing.JRadioButton();
        hasCardiacRadioNo = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(153, 153, 255));

        getAlertFromHH.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        getAlertFromHH.setText("Manage Vital Signs");

        shareInfoGroup.add(shareVitalInfoJRadioYes);
        shareVitalInfoJRadioYes.setText("Yes");
        shareVitalInfoJRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareVitalInfoJRadioYesActionPerformed(evt);
            }
        });

        shareInfoGroup.add(shareVitalInfoJRadioNo);
        shareVitalInfoJRadioNo.setText("No");
        shareVitalInfoJRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareVitalInfoJRadioNoActionPerformed(evt);
            }
        });

        shareInfo.setText("Would you like to share Vital Sign Information with us :");

        submitVitalSignsJBtn.setText("Submit");
        submitVitalSignsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVitalSignsJBtnActionPerformed(evt);
            }
        });

        cancelJBtn.setText("Cancel");

        vitalSignPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        hasSensorGroup.add(hasSensorRadioYes);
        hasSensorRadioYes.setText("Yes");
        hasSensorRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasSensorRadioYesActionPerformed(evt);
            }
        });

        respRateCheckBox.setText("Respiratory Rate");

        getAlertsGroup.add(getAlertJRadioYes);
        getAlertJRadioYes.setText("Yes");
        getAlertJRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAlertJRadioYesActionPerformed(evt);
            }
        });

        sysBPCheckBox.setText("Systollic Blood Pressure");

        weightCheckBox.setText("Weight");

        getAlert.setText("Would you like to get alert from Heart Help:");

        sensorDevice.setText("Do you have a sensor device to track Vital Signs");

        getAlertsGroup.add(getAlertJRadioNo);
        getAlertJRadioNo.setText("No");
        getAlertJRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAlertJRadioNoActionPerformed(evt);
            }
        });

        vitalSignsTrck.setText("Please Select Vital Signs you would like to track:");

        hasSensorGroup.add(hasSensorRadioNo);
        hasSensorRadioNo.setText("No");
        hasSensorRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasSensorRadioNoActionPerformed(evt);
            }
        });

        heartRateChckBox.setText("Heart Rate");

        javax.swing.GroupLayout vitalSignPanelLayout = new javax.swing.GroupLayout(vitalSignPanel);
        vitalSignPanel.setLayout(vitalSignPanelLayout);
        vitalSignPanelLayout.setHorizontalGroup(
            vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalSignPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vitalSignsTrck, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sensorDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAlert))
                .addGap(58, 58, 58)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightCheckBox)
                    .addComponent(sysBPCheckBox)
                    .addGroup(vitalSignPanelLayout.createSequentialGroup()
                        .addComponent(getAlertJRadioYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getAlertJRadioNo))
                    .addGroup(vitalSignPanelLayout.createSequentialGroup()
                        .addComponent(hasSensorRadioYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasSensorRadioNo))
                    .addComponent(respRateCheckBox)
                    .addComponent(heartRateChckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        vitalSignPanelLayout.setVerticalGroup(
            vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalSignPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sensorDevice)
                    .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hasSensorRadioYes)
                        .addComponent(hasSensorRadioNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vitalSignsTrck)
                    .addComponent(heartRateChckBox))
                .addGap(18, 18, 18)
                .addComponent(respRateCheckBox)
                .addGap(18, 18, 18)
                .addComponent(sysBPCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weightCheckBox)
                .addGap(21, 21, 21)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAlert)
                    .addComponent(getAlertJRadioYes)
                    .addComponent(getAlertJRadioNo))
                .addGap(53, 53, 53))
        );

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        cardiacProblems.setText("Do you have Cardiac problems ");

        hasCardiacProbGroup.add(hasCardiacYes);
        hasCardiacYes.setText("Yes");
        hasCardiacYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasCardiacYesActionPerformed(evt);
            }
        });

        hasCardiacProbGroup.add(hasCardiacRadioNo);
        hasCardiacRadioNo.setText("No");
        hasCardiacRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasCardiacRadioNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backJButton)
                        .addGap(268, 268, 268)
                        .addComponent(submitVitalSignsJBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelJBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(getAlertFromHH, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vitalSignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(365, 365, 365)
                                                .addComponent(hasCardiacYes))
                                            .addComponent(cardiacProblems))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hasCardiacRadioNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shareInfo)
                                        .addGap(18, 18, 18)
                                        .addComponent(shareVitalInfoJRadioYes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(shareVitalInfoJRadioNo)))))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(getAlertFromHH)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shareVitalInfoJRadioYes)
                    .addComponent(shareVitalInfoJRadioNo)
                    .addComponent(shareInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardiacProblems)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hasCardiacYes)
                        .addComponent(hasCardiacRadioNo)))
                .addGap(18, 18, 18)
                .addComponent(vitalSignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(cancelJBtn)
                    .addComponent(submitVitalSignsJBtn))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitVitalSignsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVitalSignsJBtnActionPerformed
      

    }//GEN-LAST:event_submitVitalSignsJBtnActionPerformed
    
    public void resetFields()
    {
        hasCardiacYes.setSelected(false);
        hasCardiacRadioNo.setSelected(false);
        shareVitalInfoJRadioNo.setSelected(false);
        shareVitalInfoJRadioYes.setSelected(false);
        hasSensorRadioYes.setSelected(false);
        hasSensorRadioNo.setSelected(false);
        heartRateChckBox.setSelected(false);
        respRateCheckBox.setSelected(false);
        sysBPCheckBox.setSelected(false);
        weightCheckBox.setSelected(false);
        getAlertJRadioYes.setSelected(false);
        getAlertJRadioNo.setSelected(false);
    }
       

    private void shareVitalInfoJRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareVitalInfoJRadioYesActionPerformed
         
         person.setShareVitalInfo(true);
         if(hasCardiacYes.isSelected())
         {
           vitalSignPanel.setVisible(true);   
         }
           
    }//GEN-LAST:event_shareVitalInfoJRadioYesActionPerformed

    private void shareVitalInfoJRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareVitalInfoJRadioNoActionPerformed
         person.setShareVitalInfo(false);
         vitalSignPanel.setVisible(false);
    }//GEN-LAST:event_shareVitalInfoJRadioNoActionPerformed

    private void hasSensorRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasSensorRadioYesActionPerformed
       person.setHasSensorDevice(true);
       
    }//GEN-LAST:event_hasSensorRadioYesActionPerformed

    private void hasSensorRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasSensorRadioNoActionPerformed
        person.setHasSensorDevice(false);
    }//GEN-LAST:event_hasSensorRadioNoActionPerformed

    private void getAlertJRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAlertJRadioYesActionPerformed
       person.setGetAlerts(true);
    }//GEN-LAST:event_getAlertJRadioYesActionPerformed

    private void getAlertJRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAlertJRadioNoActionPerformed
        person.setGetAlerts(false);
    }//GEN-LAST:event_getAlertJRadioNoActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void hasCardiacYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasCardiacYesActionPerformed
        person.setHasCardiacProb(true);
        if(shareVitalInfoJRadioYes.isSelected())
        {
        vitalSignPanel.setVisible(true);
        }
    }//GEN-LAST:event_hasCardiacYesActionPerformed

    private void hasCardiacRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasCardiacRadioNoActionPerformed
       person.setHasCardiacProb(false);
        vitalSignPanel.setVisible(false);
    }//GEN-LAST:event_hasCardiacRadioNoActionPerformed
  
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelJBtn;
    private javax.swing.JLabel cardiacProblems;
    private javax.swing.JLabel getAlert;
    private javax.swing.JLabel getAlertFromHH;
    private javax.swing.JRadioButton getAlertJRadioNo;
    private javax.swing.JRadioButton getAlertJRadioYes;
    private javax.swing.ButtonGroup getAlertsGroup;
    private javax.swing.ButtonGroup hasCardiacProbGroup;
    private javax.swing.JRadioButton hasCardiacRadioNo;
    private javax.swing.JRadioButton hasCardiacYes;
    private javax.swing.ButtonGroup hasSensorGroup;
    private javax.swing.JRadioButton hasSensorRadioNo;
    private javax.swing.JRadioButton hasSensorRadioYes;
    private javax.swing.JCheckBox heartRateChckBox;
    private javax.swing.JCheckBox respRateCheckBox;
    private javax.swing.ButtonGroup sendToDoctorGroup;
    private javax.swing.JLabel sensorDevice;
    private javax.swing.JLabel shareInfo;
    private javax.swing.ButtonGroup shareInfoGroup;
    private javax.swing.JRadioButton shareVitalInfoJRadioNo;
    private javax.swing.JRadioButton shareVitalInfoJRadioYes;
    private javax.swing.JButton submitVitalSignsJBtn;
    private javax.swing.JCheckBox sysBPCheckBox;
    private javax.swing.JPanel vitalSignPanel;
    private javax.swing.JLabel vitalSignsTrck;
    private javax.swing.JCheckBox weightCheckBox;
    // End of variables declaration//GEN-END:variables

 
}
